/* EntityJS v0.2 http://entityjs.com | License http://entityjs.com/license */
if(!path) path = '';
document.write("<script src='"+path+"src/entityjs/core/re.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/core/component.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/core/entity.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/core/load.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/core/query.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/core/system.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/cycle/draw.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/cycle/ticker.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/cycle/update.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/cycle/worker.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/display/bar.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/display/bitfont.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/display/bitmap.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/display/font.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/display/sprimate.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/display/sprite.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/input/keyboard.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/input/mouse.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/input/pressed.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/bind.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/bisect.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/drag.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/group.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/hitmap.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/physics.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/point.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/position.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/radius.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/screen.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/size.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/tile.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/tween.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/media/channel.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/media/playlist.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/media/sound.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/pattern/arraymap.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/save/database.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/save/storage.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/util/log.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/util/polyfill.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/util/random.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/util/scene.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/util/sheet.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/util/support.js' language='javascript'><\/script>");

window.onload = function(){ re.version = '0.2'; }