/* EntityJS v0.1 http://entityjs.com | License http://entityjs.com/license */
if(!path) path = '';
document.write("<script src='"+path+"src/entityjs/re.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/core/component.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/core/entity.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/core/load.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/core/query.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/core/system.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/cycle/draw.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/cycle/interval.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/cycle/sprimate.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/cycle/tick.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/cycle/update.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/cycle/worker.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/display/bitmap.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/display/particle.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/display/shape.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/display/sprite.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/display/text.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/input/keyboard.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/input/mouse.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/input/pressed.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/bounds.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/drag.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/group.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/idgrid.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/physics.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/point.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/radius.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/size.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/math/tile.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/media/sound.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/net/socket.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/pattern/map.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/storage/database.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/storage/storage.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/util/scene.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/util/sheet.js' language='javascript'><\/script>");
document.write("<script src='"+path+"src/entityjs/util/support.js' language='javascript'><\/script>");

window.onload = function(){ re.version = '0.1'; }